### PR TITLE
Add documentation on environment variables

### PR DESCRIPTION
**Pull request by daleglass**
This adds a complete list of all the environment variables used in the source tree.

### CODE REVIEW

**Review by JulianGro — CHANGES_REQUESTED** [review]
So we already have two lists of environment variables: https://docs.vircadia.dev/developer/interface/environment-variables.html https://docs.vircadia.dev/developer/domain-server/environment-variables.html
I guess we would need to restructure the documentation there, so it makes sense.

Also I am not sure how you are trying to do those tables, but it doesn't work like that:
1Auswahl_790

**Comment by daleglass** [comment]
Yeah, it might be a bit superfluous and need some thought about how to organize it. I wanted a source-wide authoritative list of everything, which this should be.

Hrm. That is strange. It worked for me with an online editor (https://stackedit.io/), and the `markdown` command from "discount".

**Comment by daleglass** [comment]
Ok, that should have fixed it

**Review by JulianGro — APPROVED** [review]
Line 43 and 46 aren't exactly great, but I guess it's better than nothing.

**Comment by digisomni** [comment]
There seems to be overlap on where these environment variables can go. There are existing .md lists in the Interface, Assignment Client, and Domain Server sections, so for whatever won't fit in for those then I think a misc. file might be appropriate?

**Comment by JulianGro** [comment]
I have started reorganizing the developer section and will add this list there as well.

**Comment by digisomni** [comment]
Awesome!

**Comment by JulianGro** [comment]
Should be moved to https://github.com/vircadia/vircadia-dev-docs

**Pull request closed without merging**
