### PR TITLE
Add some missing environment variables that can be used during build

### PR DESCRIPTION
**Pull request by daleglass**

### CODE REVIEW

**Comment by digisomni** [comment]
This should be added in the build docs in the main Vircadia repo. This file gets pulled from there.

**Comment by daleglass** [comment]
Hmm, should the file be at all in this repo then?

**Comment by digisomni** [comment]
I'd say so because it allows a person to find developer docs in the docs if they are looking but it also means that for developers who look for build info with the source will find what they need there. Two birds, one stone and all that. :)

**Comment by daleglass** [comment]
So should I change this to a PR against the main repo, or does it need to change in both at once?

**Comment by digisomni** [comment]
Just in the main repo. Whenever someone builds the docs it gets automatically pulled so they can commit it in their PR.

**Comment by daleglass** [comment]
Ok.

**Comment by JulianGro** [comment]
Yeah I have been thinking that it would make more sense to use git hooks to get the file on every checkout instead of having it in the repo.

**Comment by digisomni** [comment]
That might be a pretty handy way to do it.

**Pull request closed without merging**
