### PR TITLE
 Removed high-fidelity wording on architecture images

### PR DESCRIPTION
**Pull request by Madders**
Some branding changes to the architecture diagrams that remove high-fidelity and marketplace and replace with the vircadia wording from the documentation body text.

The font I used was Roboto, which isn't an exact match but was pretty similar.

### CODE REVIEW

**Review by JulianGro — APPROVED** [review]
While I feel like we should make it more clear that people can host their own Metaverse services, that side of the software doesn't seem practical yet and we *do* host a Metaverse service so this seems good for now.

**Comment by JulianGro** [comment]
Could you add the font name(s) you used to the PR description?

**Comment by Madders** [comment]
The font I used was Roboto, which isn't an exact match but was pretty similar.

**Review by digisomni — APPROVED** [review]
Looks good to me! :)

**Pull request merged**
