### PR TITLE
Add french language

### PR DESCRIPTION
**Pull request by JulianGro**
This PR adds french as requested by a Weblate user.

Since the PR-builds never worked as I originally expected I also took this opportunity to change them. They only check for warnings now, rather than trying to upload anything which doesn't work. Obviously they will always fail for now, since there is still >100 warnings.

Keep in mind that the files in docs/source/locales do not need review as they are generated by sphinx and will be automatically updated by Weblate once the PR is merged.

A preview is available here: https://data.moto9000.moe/sphinx/%23107/ ( dd4635c )

### CODE REVIEW

**Comment by digisomni** [comment]
One thing of note is that over 100 warnings always show up on the first build, if you build again you get about only 15 warnings which are understood warnings. I'm not sure why this is, maybe a race condition on Sphinx.

As for my own test of the build, it shows only 15 warnings after rebuilding which is what I expect to see. Overall, looks fine to me. (ignoring all of the Weblate related stuff.)

**Comment by JulianGro** [comment]
> One thing of note is that over 100 warnings always show up on the first build, if you build again you get about only 15 warnings which are understood warnings. I'm not sure why this is, maybe a race condition on Sphinx.
> 
> As for my own test of the build, it shows only 15 warnings after rebuilding which is what I expect to see. Overall, looks fine to me. (ignoring all of the Weblate related stuff.)

It shows less warnings when building again, because it is only building again what it thinks it needs to.
The warnings are all valid.

**Comment by digisomni** [comment]
In that case, the major problem that Sphinx has is that it doesn't support .md as well as it should... But that's something for another time.

**Review by digisomni — APPROVED** [review]
Seems good to me.

**Pull request merged**
