### PR TITLE
Relocate contribution guide to the website.

### PR DESCRIPTION
**Pull request by digisomni**
The contribution guide isn't necessarily a user oriented exclusively, nor does it have only developer aspects to it. It seems to be best served from the website directly. This will make it easier to update and also style to make it appealing for potential contributors.

https://vircadia.com/contribute/

### CODE REVIEW

**Comment by digisomni** [comment]
I am able to make it more attractive, as linked. Plus it's a bit dev-vy so it doesn't belong in the user docs either. But not so dev-vy that it should go in the dev docs. Trying to trim fat and get things where I can work on them efficiently, in this case, specifically with regards to recruiting new contributorship.

**Comment by JulianGro** [comment]
If we are talking about function, there is a couple of issues with that webpage.
- Text is far too low contrast and is had to read on any device I can think of.
- The page has slow animations that move it while you already want to read, making it harder to get an overview.
- A lot of vertical space is wasted by big logos that don't add anything, making it even harder to get an overview.
- There is useless clutter on the page which adds noise and makes it harder to find what you are looking for. Mainly I mean the quote on the side that is useless and also written in a hard to read font, making it harder to check if that is useful information to the viewer.
- The boxes animating in are also annoying, because the viewer has to wait for the animation to finish before being able to read them. This might not seem like much, but when I view a web page like this I already assume the next header is going to in line with the ones above. Then they show up in the middle of the screen, making me readjust, and then they move to the side again. It also, again, makes it harder to get an overview of the page because you need to wait for stuff to show up.

**Comment by digisomni** [comment]
Otherwise, the syntax appears to be fine and there are no warnings reported by the checks.

**Comment by JulianGro** [comment]
That Weblate push just reminded me that there is another reason why this should be in the docs:
https://docs.vircadia.com/fr/contribute.html
https://docs.vircadia.com/es/contribute.html

Considering we have full translations for this on the docs, and the website doesn't have good (or currently any) translations support, I am rejecting this PR.
I don't see why we should inconvenience the readers *and* exclude non-english speakers (especially since the translation gets suggested as a way to contribute) for what is at best a miniscule maintainance improvement.

**Comment by Penguin-Guru** [comment]
I think it's a significant improvement to add that page to the main site, but not worth losing the translations. I suppose the best options would be to apply the translations to the main site or maintain the information in both places. Either way would probably be a nuisance but I'm no web dev.

**Comment by digisomni** [comment]
Because the user docs should be primarily focused on delivering, well, documentation on how to use the platform for the user. Currently, it takes on too much outside of that purely for the sake of translation (which is understandable, to an extent). Regardless, trimming is needed. Similarly, the developer docs are meant to advise and inform developers on how to use/implement the platform correctly.

As for having two copies, there shouldn't be odd copies laying around that might conflict or confuse, there were numerous issues in the page already for example. I update and revise verbiage regularly, going through Git makes this process a lengthy process to do often, especially where appealing to new users and contributors is involved.

Translation wise, I've added some translation support to the website. Check it out (top right of the screen): https://vircadia.com/contribute/

Ultimately, I don't think user-generated translation (as opposed to existing translation tools) is a good enough reason to try and replicate all material relating to Vircadia in the user docs.

**Comment by Penguin-Guru** [comment]
I think that's fine for now, as long as other people are fine with it, but you might still want to use that kind of testing sub-domain and version control for testing and getting opinions on stuff. Something to consider.

**Pull request merged**
