### PR TITLE
Fix remaining warnings

### LINKED ISSUE #110: Sphinx cannot parse all links from build docs
The build docs contain links which are not parseable by Sphinx.
Example:
```
Follow the [build guide](BUILD.md) to figure out how to build Vircadia for your platform.
```
Would need to be:
```
Follow a [build guide](../BUILD_GENERAL) to figure out how to build Vircadia for your platform.
```

### PR DESCRIPTION
**Pull request by JulianGro**
This PR fixes the rest of the warnings that come from this repo. Some warnings are still coming from files that come from the main vircadia repo.

Fixes #110 

A preview is available here: https://data.moto9000.moe/sphinx/PR124/ (c1e1eee)

### CODE REVIEW

**Comment by JulianGro** [comment]
With the last commit I added functionality to the Makefile that fixes the hyperlinks that break when importing the build documentation from the main repository.

**Comment by ctrlaltdavid** [comment]
On Windows...
- Before (i.e., current master): 10 build warnings
- after (i.e., this PR): 4 build warnings
```
D:\Workspaces\CtrlAltStudio\Vircadia-Docs-Sphinx\Vircadia-Docs-Sphinx\docs\source\developer\build\BUILD.md:35: WARNING: None:any reference target not found: cmake/externals
D:\Workspaces\CtrlAltStudio\Vircadia-Docs-Sphinx\Vircadia-Docs-Sphinx\docs\source\developer\build\BUILD.md:150: WARNING: None:any reference target not found: cmake/modules/
D:\Workspaces\CtrlAltStudio\Vircadia-Docs-Sphinx\Vircadia-Docs-Sphinx\docs\source\developer\build\BUILD.md:178: WARNING: None:any reference target not found: interface/external
D:\Workspaces\CtrlAltStudio\Vircadia-Docs-Sphinx\Vircadia-Docs-Sphinx\docs\source\developer\installer\INSTALLER.md:5: WARNING: None:any reference target not found: BUILD
```

**Comment by JulianGro** [comment]
Those warnings are fixed in the Makefile. Windows uses a batch file which I didn't even bother looking at. It doesn't seem nearly as important and Windows shell is just extremely limited.
We could have people install `GNU sed` via chocolatey and just use the same command as on Linux, but at that point we might as well just have them install `GNU make` as well which probably makes Windows users able to use the Makefile.

Whatever we do, I would like a Windows person to make a PR if the really want to go through the trouble for 4 warnings.

**Review by ctrlaltdavid — APPROVED** [review]

**Review by digisomni — APPROVED** [review]

**Comment by daleglass** [comment]
Probably should use PowerShell instead for Windows builds, but that's definitely for later

**Pull request merged**
